"""
Trello Integration Service
Syncs tasks and project boards with Trello via REST API.

API Key is provided by the client; the API Token must be generated by
authorizing Digital Dada's Power-Up / integration against the client's
Trello workspace (see https://trello.com/1/authorize).
"""

import logging
from typing import Dict, List, Optional

import httpx

from app.core.config import settings

logger = logging.getLogger(__name__)

TRELLO_BASE_URL = "https://api.trello.com/1"


class TrelloService:
    """Handles all Trello board/card operations."""

    def __init__(self):
        self.api_key = settings.TRELLO_API_KEY
        self.api_token = settings.TRELLO_API_TOKEN
        self.board_id = settings.TRELLO_BOARD_ID
        self._configured = bool(self.api_key and self.api_token)

        if not self._configured:
            logger.warning(
                "Trello service partially configured – API Key present but "
                "API Token is missing.  Card sync will be skipped until the "
                "token is provided."
            )

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _auth_params(self) -> Dict[str, str]:
        """Base query-string authentication params."""
        return {"key": self.api_key, "token": self.api_token}

    async def _request(
        self, method: str, path: str, **kwargs
    ) -> Optional[Dict]:
        """Make an authenticated request to the Trello API."""
        if not self._configured:
            logger.debug("Trello request skipped – service not fully configured.")
            return None

        url = f"{TRELLO_BASE_URL}{path}"
        params = {**self._auth_params(), **kwargs.pop("params", {})}

        async with httpx.AsyncClient(timeout=15) as client:
            resp = await client.request(method, url, params=params, **kwargs)
            resp.raise_for_status()
            return resp.json()

    # ------------------------------------------------------------------
    # Board helpers
    # ------------------------------------------------------------------

    async def get_boards(self) -> List[Dict]:
        """Return all boards visible to the authenticated user."""
        result = await self._request("GET", "/members/me/boards")
        return result or []

    async def get_lists(self, board_id: Optional[str] = None) -> List[Dict]:
        """Return lists (columns) on a board."""
        bid = board_id or self.board_id
        if not bid:
            logger.error("No board_id configured for Trello.")
            return []
        result = await self._request("GET", f"/boards/{bid}/lists")
        return result or []

    async def get_list_id_by_name(
        self, name: str, board_id: Optional[str] = None
    ) -> Optional[str]:
        """Find a list by name and return its ID."""
        lists = await self.get_lists(board_id)
        for lst in lists:
            if lst.get("name", "").lower() == name.lower():
                return lst["id"]
        return None

    # ------------------------------------------------------------------
    # Card CRUD
    # ------------------------------------------------------------------

    async def create_card(
        self,
        list_id: str,
        name: str,
        description: str = "",
        due_date: Optional[str] = None,
        labels: Optional[List[str]] = None,
    ) -> Optional[Dict]:
        """Create a new Trello card on the given list.

        Args:
            list_id: Target list (column) ID.
            name: Card title.
            description: Card description / body.
            due_date: ISO-8601 due date string (optional).
            labels: List of label IDs to attach (optional).

        Returns:
            Created card dict or None if service is unconfigured.
        """
        payload: Dict = {
            "idList": list_id,
            "name": name,
            "desc": description,
        }
        if due_date:
            payload["due"] = due_date
        if labels:
            payload["idLabels"] = ",".join(labels)

        try:
            result = await self._request("POST", "/cards", params=payload)
            if result:
                logger.info(f"Trello card created: {result.get('id')} – {name}")
            return result
        except Exception as exc:
            logger.error(f"Error creating Trello card: {exc}")
            return None

    async def update_card(
        self, card_id: str, **fields
    ) -> Optional[Dict]:
        """Update fields on an existing Trello card."""
        try:
            result = await self._request(
                "PUT", f"/cards/{card_id}", params=fields
            )
            if result:
                logger.info(f"Trello card updated: {card_id}")
            return result
        except Exception as exc:
            logger.error(f"Error updating Trello card {card_id}: {exc}")
            return None

    async def move_card(
        self, card_id: str, list_id: str
    ) -> Optional[Dict]:
        """Move a card to a different list (column)."""
        return await self.update_card(card_id, idList=list_id)

    async def add_comment(
        self, card_id: str, text: str
    ) -> Optional[Dict]:
        """Add a comment to a Trello card."""
        try:
            result = await self._request(
                "POST",
                f"/cards/{card_id}/actions/comments",
                params={"text": text},
            )
            return result
        except Exception as exc:
            logger.error(f"Error adding comment to card {card_id}: {exc}")
            return None

    async def get_cards(
        self, list_id: Optional[str] = None, board_id: Optional[str] = None
    ) -> List[Dict]:
        """Get cards from a specific list or the whole board."""
        if list_id:
            result = await self._request("GET", f"/lists/{list_id}/cards")
        else:
            bid = board_id or self.board_id
            if not bid:
                return []
            result = await self._request("GET", f"/boards/{bid}/cards")
        return result or []

    async def delete_card(self, card_id: str) -> bool:
        """Delete a Trello card."""
        try:
            await self._request("DELETE", f"/cards/{card_id}")
            logger.info(f"Trello card deleted: {card_id}")
            return True
        except Exception as exc:
            logger.error(f"Error deleting Trello card {card_id}: {exc}")
            return False

    # ------------------------------------------------------------------
    # High-level helpers (used by task_service)
    # ------------------------------------------------------------------

    async def sync_task_to_trello(
        self,
        task_title: str,
        task_description: str,
        target_list_name: str = "To Do",
        due_date: Optional[str] = None,
    ) -> Optional[Dict]:
        """Convenience: create a card on the named list.

        Looks up the list by name, then creates a card.
        """
        list_id = await self.get_list_id_by_name(target_list_name)
        if not list_id:
            logger.warning(
                f"Trello list '{target_list_name}' not found on board "
                f"{self.board_id}. Card not created."
            )
            return None

        return await self.create_card(
            list_id=list_id,
            name=task_title,
            description=task_description,
            due_date=due_date,
        )


# ---------------------------------------------------------------------------
# Singleton accessor
# ---------------------------------------------------------------------------

_trello_service: Optional[TrelloService] = None


def get_trello_service() -> TrelloService:
    """Get or create the Trello service singleton."""
    global _trello_service
    if _trello_service is None:
        _trello_service = TrelloService()
    return _trello_service
